# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoveSoApple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoveSoApple
  pod 'OMJoystick'
  pod 'SFSafeSymbols' 

  target 'RoveSoAppleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoveSoAppleUITests' do
    # Pods for testing
  end

end
